"""add tenant user kb doc tables

Revision ID: 50d84d83ad0e
Revises: f6c7458fff25
Create Date: 2026-05-22 11:37:34.913563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d84d83ad0e'
down_revision: Union[str, Sequence[str], None] = 'f6c7458fff25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
